### ISSUE TITLE
Postgres Error (Invalid text representation)

### ISSUE THREAD

**Issue by agreif** [libasys/calendarplus#147]
Hi, with 1.0.8 on postgres 9.4.4 I have the following Exception:
caused by the url:
https://server/index.php/apps/calendarplus/calendarsettingsgetusersettingscalendar"

it happens with some users, but not all.

```
{"reqId":"P6NF6Z\/mF+MFJQScgZXa",
"remoteAddr":"5.45.101.146",
"app":"index",
"message":"Exception: {"Exception":"Doctrine/DBAL/Exception/DriverException",
"Message":"An exception occurred while executing 'SELECT * FROM "oc_clndrplus_objects" WHERE "calendarid" = ? ' with params ["birthday_some.user"]:
SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "birthday_some.user"",
"Code":0,
"Trace":"#0 /owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(116): Doctrine/DBAL/Driver/AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine/DBAL/Driver/PDOException))
#1 /owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(172): Doctrine/DBAL/DBALException::driverExceptionDuringQuery(Object(Doctrine/DBAL/Driver/PDOPgSql/Driver), Object(Doctrine/DBAL/Driver/PDOException), 'SELECT * FROM "...', Array)
#2 /owncloud/lib/private/db/statementwrapper.php(73): Doctrine/DBAL/Statement->execute(Array)
#3 /owncloud/apps/calendarplus/lib/object.php(44): OC_DB_StatementWrapper->execute(Array)
#4 /owncloud/apps/calendarplus/lib/app.php(351): OCA/CalendarPlus/Object::all('birthday_some....')
#5 /owncloud/apps/calendarplus/lib/app.php(234): OCA/CalendarPlus/App::scanCategories()
#6 /owncloud/apps/calendarplus/lib/app.php(335): OCA/CalendarPlus/App::getVCategories()
#7 /owncloud/apps/calendarplus/lib/app.php(309): OCA/CalendarPlus/App::getCategoryOptions()
#8 /owncloud/apps/calendarplus/controller/calendarsettingscontroller.php(123): OCA/CalendarPlus/App::loadTags()
#9 [internal function]: OCA/CalendarPlus/Controller/CalendarSettingsController->getUserSettingsCalendar()
#10 /owncloud/lib/private/appframework/http/dispatcher.php(159): call_user_func_array(Array, Array)
#11 /owncloud/lib/private/appframework/http/dispatcher.php(89): OC/AppFramework/Http/Dispatcher->executeController(Object(OCA/CalendarPlus/Controller/CalendarSettingsController), 'getUserSettings...')
#12 /owncloud/lib/private/appframework/app.php(108): OC/AppFramework/Http/Dispatcher->dispatch(Object(OCA/CalendarPlus/Controller/CalendarSettingsController), 'getUserSettings...')
#13 /owncloud/lib/private/appframework/routing/routeactionhandler.php(45): OC/AppFramework/App::main('CalendarSetting...', 'getUserSettings...', Object(OC/AppFramework/DependencyInjection/DIContainer), Array)
#14 [internal function]: OC/AppFramework/routing/RouteActionHandler->__invoke(Array)
#15 /owncloud/lib/private/route/router.php(274): call_user_func(Object(OC/AppFramework/routing/RouteActionHandler), Array)
#16 /owncloud/lib/base.php(873): OC/Route/Router->match('/apps/calendarp...')
#17 /owncloud/index.php(40): OC::handleRequest()
#18 {main}",
"File":"/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php",
"Line":91}",
"level":4,
"time":"2015-09-02T10:47:25+00:00",
"method":"GET",
"url":"\/index.php\/apps\/calendarplus\/calendarsettingsgetusersettingscalendar"}
```

**Comment by agreif** [comment]
in postgres the table hast the following schema:

```
owncloud=# \d oc_clndrplus_objects
                                        Table "public.oc_clndrplus_objects"
    Column    |              Type              |                             Modifiers                             
--------------+--------------------------------+-------------------------------------------------------------------
 id           | integer                        | not null default nextval('oc_clndrplus_objects_id_seq'::regclass)
 calendarid   | integer                        | not null default 0
 objecttype   | character varying(40)          | not null default ''::character varying
 startdate    | timestamp(0) without time zone | default '1970-01-01 00:00:00'::timestamp without time zone
 enddate      | timestamp(0) without time zone | default '1970-01-01 00:00:00'::timestamp without time zone
 repeating    | integer                        | default 0
 summary      | character varying(255)         | default NULL::character varying
 calendardata | text                           | 
 uri          | character varying(255)         | default NULL::character varying
 lastmodified | integer                        | default 0
 isalarm      | smallint                       | not null default 0
 org_objid    | integer                        | not null default 0
 userid       | character varying(200)         | default NULL::character varying
 eventuid     | character varying(255)         | default NULL::character varying
 relatedto    | character varying(255)         | default NULL::character varying
Indexes:
    "oc_clndrplus_objects_pkey" PRIMARY KEY, btree (id)

```

**Comment by agreif** [comment]
I assume that the problem is in the method scanCategories() line 351

```
$calendar_events = Object::all($calendar['id']);
```

$calendar['id'] does not return the content of the DB column 'id' but some other php internal id that has the string representation like birthday_<calendar.userid>

in my situation the user has the ID 7 in the DB and if I  change the code to

```
Object::all("XX".$calendar['id']);
```

then somehow I get 

```
select ... from ... where calendarid = "XX7"

Object::all(array_values($calendar['id']));
-> with params [[7,\\\"some.user\\\",\\\"some.user\\\",\\\"some.user\\\",1,1,0,\\\"#C2F9FC ...

Object::all(array_keys($calendar['id']));
with params [[\\\"id\\\",\\\"userid\\\",\\\"displayname\\\",\\\"uri\\\",\\\"active\\\",\\\"ctag\\\"
```

Alex.

**Comment by agreif** [comment]
I figured out where the string ist set:
in file hooks.php line 52 in method function getBirthdayCalender

```
$Calendar=array(
    ...
    'id'=>'birthday_'. \OCP\USER::getUser(),                                                                                            
```

this seems to affect the DB select statement.

and this hook is called in app.php:

```
\OCP\Util::connectHook('OCA\CalendarPlus', 'getCalendars', 'OCA\ContactsPlus\Hooks', 'getBirthdayCalender');
```

**Comment by libasys** [comment]
can you test current master i commited a possible fix?

**Comment by agreif** [comment]
yes, this fixed it.
the calendars, are now showing fine for all users
thanks.

why do you think it is a "possible" fix and not the "definitive" fix?

Alex.

**Comment by libasys** [comment]
possible fix cause i have no postgresql db for testing! ;)

**Comment by agreif** [comment]
verstehe :))
thanks for the quick fix, and keep up the good work.

you can close the ticket.
Alex.
