### ISSUE TITLE
Failed to start calendar app on OC 8.1

### ISSUE THREAD

**Issue by UnnamedHero** [libasys/calendarplus#4]
After starting calendarplus app.
OC: CentOS 7.1.1503, Owncloud 8.1 Release.

DB: Postgresql

```
 An exception occurred while executing 'INSERT INTO "oc_clndrplus_calendars" 
("userid","displayname","uri","ctag","calendarorder","calendarcolor","timezone","components","issubscr
ibe","externuri","lastmodifieddate") VALUES(?,?,?,?,?,?,?,?,?,?,?)' with params ["WOW", "WOW", 
"WOW", 1, 0, "#C2F9FC", null, "VEVENT,VTODO,VJOURNAL", false, "", 1436313866]: 
SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: ""

Файл: /mnt/sdc/www/qqo/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php
Линия: 91
```

```
#0 /mnt/sdc/www/qqo/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(116): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 /mnt/sdc/www/qqo/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(172): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO "oc...', Array)
#2 /mnt/sdc/www/qqo/lib/private/db/statementwrapper.php(73): Doctrine\DBAL\Statement->execute(Array)
#3 /mnt/sdc/www/qqo/apps/calendarplus/lib/calendar.php(176): OC_DB_StatementWrapper->execute(Array)
#4 /mnt/sdc/www/qqo/apps/calendarplus/lib/calendar.php(207): OCA\CalendarPlus\Calendar::addCalendar('WOW', 'WOW')
#5 /mnt/sdc/www/qqo/apps/calendarplus/controller/pagecontroller.php(58): OCA\CalendarPlus\Calendar::addDefaultCalendars('WOW')
#6 [internal function]: OCA\CalendarPlus\Controller\PageController->index()
#7 /mnt/sdc/www/qqo/lib/private/appframework/http/dispatcher.php(159): call_user_func_array(Array, Array)
#8 /mnt/sdc/www/qqo/lib/private/appframework/http/dispatcher.php(89): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\CalendarPlus\Controller\PageController), 'index')
#9 /mnt/sdc/www/qqo/lib/private/appframework/app.php(108): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\CalendarPlus\Controller\PageController), 'index')
#10 /mnt/sdc/www/qqo/lib/private/appframework/routing/routeactionhandler.php(45): OC\AppFramework\App::main('PageController', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#11 [internal function]: OC\AppFramework\routing\RouteActionHandler->__invoke(Array)
#12 /mnt/sdc/www/qqo/lib/private/route/router.php(274): call_user_func(Object(OC\AppFramework\routing\RouteActionHandler), Array)
#13 /mnt/sdc/www/qqo/lib/base.php(867): OC\Route\Router->match('/apps/calendarp...')
#14 /mnt/sdc/www/qqo/index.php(40): OC::handleRequest()
#15 {main}
```

**Comment by libasys** [comment]
Hi @UnnamedHero thanks for your bug report! How familiar you are to php, to change something for testing?

**Comment by UnnamedHero** [comment]
I can test, may be I can write something simple. My php skills enough for phpinfo(), but I can try.   (:

**Comment by libasys** [comment]
Can you download the current master of calendar+ and test the bugfix, if it now works?
you only have to change the downloaded folder name from calendarplus-master to calendarplus!
Delete the old folder of calendarplus and upload the new one to your apps directory!

**Comment by UnnamedHero** [comment]
It works! (c)
