### ISSUE TITLE
Calendar+ crash and no longer functional

### ISSUE THREAD

**Issue by UnnamedHero** [libasys/calendarplus#70]
Workning with my calendar and tasks from KDE's KOrganizer and suddenly my calendar stop working. Now I can't launch calendar+ and tasks+ apps

I've got this in OC log:

```
Exception: {"Exception":"Doctrine\\DBAL\\Exception\\SyntaxErrorException","Message":"An exception occurred while executing 'SELECT * FROM \"oc_clndrplus_objects\" WHERE \"objecttype\"= ? AND ( ) ORDER BY startdate ASC' with params [\"VTODO\"]:\n\nSQLSTATE[42601]: Syntax error: 7 ERROR: syntax error at or near \")\"\nLINE 1: ..._clndrplus_objects\" WHERE \"objecttype\"= $1 AND ( ) ORDER B...\n ^","Code":0,"Trace":"#0 \/mnt\/sdc\/www\/qqo\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 \/mnt\/sdc\/www\/qqo\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Statement.php(172): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOPgSql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'SELECT * FROM \"...', Array)\n#2 \/mnt\/sdc\/www\/qqo\/lib\/private\/db\/statementwrapper.php(73): Doctrine\\DBAL\\Statement->execute(Array)\n#3 \/mnt\/sdc\/www\/qqo\/apps\/tasksplus\/lib\/app.php(307): OC_DB_StatementWrapper->execute(Array)\n#4 \/mnt\/sdc\/www\/qqo\/apps\/tasksplus\/lib\/timeline.php(142): OCA\\TasksPlus\\App::all(Array, true)\n#5 \/mnt\/sdc\/www\/qqo\/apps\/calendarplus\/controller\/pagecontroller.php(148): OCA\\TasksPlus\\Timeline->generateAddonCalendarTodo()\n#6 [internal function]: OCA\\CalendarPlus\\Controller\\PageController->index()\n#7 \/mnt\/sdc\/www\/qqo\/lib\/private\/appframework\/http\/dispatcher.php(159): call_user_func_array(Array, Array)\n#8 \/mnt\/sdc\/www\/qqo\/lib\/private\/appframework\/http\/dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\CalendarPlus\\Controller\\PageController), 'index')\n#9 \/mnt\/sdc\/www\/qqo\/lib\/private\/appframework\/app.php(108): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\CalendarPlus\\Controller\\PageController), 'index')\n#10 \/mnt\/sdc\/www\/qqo\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\\AppFramework\\App::main('PageController', 'index', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#11 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#12 \/mnt\/sdc\/www\/qqo\/lib\/private\/route\/router.php(274): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#13 \/mnt\/sdc\/www\/qqo\/lib\/base.php(867): OC\\Route\\Router->match('\/apps\/calendarp...')\n#14 \/mnt\/sdc\/www\/qqo\/index.php(40): OC::handleRequest()\n#15 {main}","File":"\/mnt\/sdc\/www\/qqo\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractPostgreSQLDriver.php","Line":66}
```

What can be done to rescue my data? Can it be fixed?

**Comment by libasys** [comment]
Please add some more information about your environment(webserver,database, ect) and explain your steps to reproduce! Thanks

**Comment by UnnamedHero** [comment]
Will do in 2-3 days. Do not close :)

**Comment by UnnamedHero** [comment]
sorry for delay, working hard. 
BTW, is it important due to #88 ?
